name: Custom Blog
favicon: null
layout_spectrum: 0.8089131768792868
typography_spectrum: 0.5783345398958772
title: Custom Blog - Home to All Things People Oriented
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0c0e'
    - '#b8d3eb'
    - '#373b3e'
    - '#79654f'
    - '#5787b2'
  brandStrength: 0.625
  lightness: 0.19433329487219453
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
